* Creating graphs                         :advanced:tutorial:zettelorg:
:PROPERTIES:
:ID:       d8e80f53-4f70-42c8-a37a-c1d4a48ba240
:END:

Beware, this is an experimental feature.

Assuming you have =graphviz= installed, you can generate vizualisations of connections between notes.

Hit =zettelorg-org-graph-note= to start from a single note, or =zettelorg-org-graph-search= to enter a search term.

Try it for yourself!
Move point to the empty space below, hit =zettelorg-org-graph-search=, and enter =#zettelorg=.
Execute the resulting code block, and then open the generated file.



The result should be a PDF with connected nodes.

Please note that you should remove the code block afterwards (or store it outside of your Zettelorg directory), so that the links inside the code block are not detected the next time you try to create a graph.

An additional tip: the search string can be empty to graph /all/ notes in Zettelorg

For more details, refer to =zettelorg.org= and look for "Creating visuals".
