#+TITLE: Link concepts
* Link concepts                                                    :tutorial:
:PROPERTIES:
:ID:       117becf4-f5e7-4c91-8919-59d91b74a4e1
:END:

Each note has a unique *ID*, which is a UUID generated by org. This note has ID =117becf4-f5e7-4c91-8919-59d91b74a4e1= IDs are stable and shouldn't change, allowing you to move entries from file to file or rename them and have your links remain the same.

Notes contain *links* to other notes. We will use id based org links. The easiest way to create a link is to “store” it from the target using =C-c l= and to insert it somewhere else using =C-c C-l=.

The other way to insert a link is to use =C-c C-l= without first storing a link. This will prompt you for the link type, target, and title you would like to insert. Out of the box, Org mode does not support “completion” of id links, making insertion of links difficult. If you like, you can use this simple method to allow completion using the “refile” mechanism of Org mode.

#+begin_src emacs-lisp :results silent
(org-link-set-parameters "id" :complete #'org-id-complete-link)

(defun org-id-complete-link ()
  "Create an id: link using completion."
  (concat "id:" (org-id-get-with-outline-path-completion org-refile-targets)))

(add-to-list 'org-agenda-text-search-extra-files '(org-agenda-files :maxlevel . 2))
#+end_src

Now you can type =C-c C-l=, then =id:=, then select from entries in your Zettelkasten via the completion mechanism.

** Navigation
:PROPERTIES:
:ID:       b5b6bc79-092f-4abb-93c5-b26e10504851
:END:
A few commands to help you navigate links include:

- =C-c C-x C-p= :: move to the previous link in the document
- =C-c C-x C-n= :: move to the next link in the document
- =C-c &= :: go back to the previous place you were
