* More Zettelorg commands                                :zettelorg:tutorial:
:PROPERTIES:
:ID:       8072f69e-53b1-4306-b458-1208e9468acd
:END:

Once you are familiar with the basics ([[id:a3e5b65f-b27c-460a-9cc0-e2b01de8b917][Zettelorg basic commands]]), it's time to learn some additional commands.

You can use the standard search for a *tag* with =M-x org-agenda m=

You can search for text using =M-x org-search-view=.

From either of these results pages, you can use =C-c l= to store links, which you can then add to a document using =C-c C-l=. You can store multiple links, and you can insert all stored links using =C-c C-M-l=. 

You can also search for test using =M-x org-occur-in-agenda-files=. This will be faster than =org-search-view= but you cannot easily extract links from it in the same way.

Because all links are kept in plain text, it can be useful to search for all notes that link to the current note. You can use =org-occur-link-in-agenda-files= to search for backlinks to the current node.

Unfortunately, out of the box this requires that the link description exactly match the title of the node. Here is an alternative solution that searchs for any backlink, no matter the description.

#+begin_src emacs-lisp :results silent
(defun zorg-backlinks ()
  "Search for backlinks to current entry."
  (interactive)
  (let ((link (condition-case nil
		  (org-id-store-link)
		(error "Unable to create a link to here"))))
    (org-occur-in-agenda-files (regexp-quote link))))
#+end_src

Let's say you've created a note, but later want to *rename* it. Just rename it - the id should remain the same.

But wait, there's more!
For some more advanced Zettelorg features, hop over to [[id:16a2419a-9838-44ae-abca-c385cb1f8db5][Advanced Zettelorg features]]
