* Start here                                         :tutorial:zettelorg:
:PROPERTIES:
:ID:       b9c8bf44-3980-4026-8737-cc546a166d31
:END:
This file guides you through a Zettlelkasten setup. You can use Org mode for a Zettlelkasten system with zero additional configuration, if you like. However, I think that you will find it easier if you use the setup outlined in this file, at least.

First, you will need to add this directory to =org-agenda-files=. Do this by executing executing =C-c C-c= on the following source block:

#+begin_src emacs-lisp :results silent
(add-to-list 'org-agenda-files default-directory)
#+end_src

The following code allows you to use =id= based links. This ensures that your links between things are stable even if you rename files or change headlines. If you already have a files in your agenda this could take some time as the id index is updated. Going forward, the index should be maintained as you add entries, so this should be a one time cost.

#+begin_src emacs-lisp :results silent
(setq org-id-link-to-org-use-id t)
(org-id-update-id-locations)
#+end_src

The one keybinding you need to know to get started, is =C-c C-o= (or =org-open-at-point=), to select links to follow.

With this knowledge, you are ready to read on.

You could
 - learn the [[id:a3e5b65f-b27c-460a-9cc0-e2b01de8b917][basic Zettelorg concepts]] 
 - look at [[id:117becf4-f5e7-4c91-8919-59d91b74a4e1][Zettelorg ID and link concepts]]
 - read about [[id:8072f69e-53b1-4306-b458-1208e9468acd][search]]
 - maybe read up on [[id:4c065f3d-7a2c-40b6-bb47-5fa2a4485f3e][Zettelorg history]]
