* Wandering to a random note             :tutorial:expansion:zettelorg:
:PROPERTIES:
:ID:       12754d84-4cc8-45fa-85a9-c36f3de21729
:END:

Sometimes it's nice to wander.

The following feature was [[https://github.com/EFLS/zettelorg/issues/53][suggested by erictleung]].

#+begin_quote
In using =org-brain=, I really liked its wander feature, which brings a note randomly.
It essentially randomly samples the notes created and displays it.
This can be helpful as an informal 'quiz' of your knowledge base or at least refresh your memory that the particular note exists.
From there you can edit it with current knowledge or link it to other notes.
#+end_quote

He proposed a function to do so, which is edited and shared below.

It will pop open the deft buffer, pick a random zettelorg ID, and enter it as a search string.

#+begin_src emacs-lisp :results silent
(defun zorg-wander ()
    "Wander through `zettelorg' notes."
    (interactive)
    (let* ((ids (hash-table-keys org-id-locations))
           (size (length ids))
           (index (random size))
           (id (nth index ids)))
      (org-id-goto id)))
#+end_src

Try running =M-x zettelorg-wander=.
It will retreive a random file from the Deft list of files, and search for its ID.

One potential issue: when there are Deft notes without an ID, the search term will be =nil=.
