* Zettelorg basic commands                               :zettelorg:tutorial:
:PROPERTIES:
:ID:       a3e5b65f-b27c-460a-9cc0-e2b01de8b917
:END:

To get started with Zettelorg, lets take a look at some basic commands.

If you come from the "[[id:5fd0aee9-99dd-462d-844b-271939c96a43][Welcome]]" note, you already know that you can *follow links* with =C-c C-o= (or ==org-open-at-point=).
This function will open the link your point is at, or will prompt you for a link to follow via =avy= keys.
Use =C-c d F= to open the link in a new window (see [[id:8072f69e-53b1-4306-b458-1208e9468acd][more commands]])

To directly *open* one of the notes in your Zettelkasten, open a file as expected.

You can *create* a new note with =C-x C-f= (=find-file=). If you want to set up a capture template to make this easier, you can and should.

That's enough to get you started.
Once you get the hang of it, take a look at [[id:8072f69e-53b1-4306-b458-1208e9468acd][more commands]] for more commands and keybindings.

If you prefer learning about IDs and links first, look [[id:117becf4-f5e7-4c91-8919-59d91b74a4e1][here]]
